services:
  postgres:
    image: postgres:latest
    container_name: banking-app
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: banking-db
    volumes:
      - banking_db_volumes:/var/lib/postgresql/data

volumes:
  banking_db_volumes: