server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/banking-db
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect